<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'app_hello_hello' => [[], ['_controller' => 'App\\Controller\\HelloController::hello'], [], [['text', '/hello']], [], []],
    'app_hello_helloname' => [['name'], ['_controller' => 'App\\Controller\\HelloController::helloName'], [], [['variable', '/', '[^/]++', 'name', true], ['text', '/hello']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'show' => [['id'], ['_controller' => 'App\\Controller\\HomeController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/show']], [], []],
    'change_locale' => [['locale'], ['_controller' => 'App\\Controller\\HomeController::changeLocale'], [], [['variable', '/', '[^/]++', 'locale', true], ['text', '/change_locale']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegisterController::index'], [], [['text', '/inscription']], [], []],
];
